---
driver:
  name: ec2
  aws_ssh_key_id: chef_newaws # key pair name
  region: ap-south-1 # region code of aws
  availability_zone: ap-south-1b # availability_zone of us-west
  subnet_id: subnet-ebe669a7 # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: ami-5b673c34 # image id of redhat 7
  #image_id: ami-0565af6e282977273 # image id of ubuntu
  security_group_ids: ["sg-098fdff61a8476c92"]


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: ./chef_newaws.pem # relative path to pem file
  connection_timeout: 10
  connection_retries: 5
 # username: ubuntu # username from ami-id
  username: ec2-user # username from ami-id

platforms:
  - name: redhat-7.5

suites:
- name: default
  run_list:
    - recipe[first_chef::default]
  verifier:
    inspec_tests:
        - test/integration/default
  attributes:


